### PR TITLE
Expose mediator topics utility to top level

### PR DESCRIPTION
**Pull request by wtrocki**
## Motivation

Expose mediator topics utility to be available as part of the mediator singleton. 
This would allow us to remove mediator dependency from all modules. 

ping @grdryn @paolobueno

### CODE REVIEW

**Comment by wtrocki** [comment]
@JameelB - we can now use this topics utility in every mediator subscriber folder and remove mediator from module dependencies..  ^^

**Comment by paolobueno** [comment]
Merging and setting up PRs on dependent modules to bump to this version.

**Comment by paolobueno** [comment]
@wtrocki @JameelB here's the list of PRs with the version bumps:

https://github.com/feedhenry-raincatcher/raincatcher-demo-auth/pull/70
https://github.com/feedhenry-raincatcher/raincatcher-demo-cloud/pull/87
https://github.com/feedhenry-raincatcher/raincatcher-demo-mobile/pull/61
https://github.com/feedhenry-raincatcher/raincatcher-demo-portal/pull/59
https://github.com/feedhenry-raincatcher/raincatcher-analytics/pull/10
https://github.com/feedhenry-raincatcher/raincatcher-appform/pull/33
https://github.com/feedhenry-raincatcher/raincatcher-camera/pull/11
https://github.com/feedhenry-raincatcher/raincatcher-file/pull/24
https://github.com/feedhenry-raincatcher/raincatcher-gps/pull/6
https://github.com/feedhenry-raincatcher/raincatcher-map/pull/19
https://github.com/feedhenry-raincatcher/raincatcher-message/pull/21
https://github.com/feedhenry-raincatcher/raincatcher-mongoose-store/pull/10
https://github.com/feedhenry-raincatcher/raincatcher-push/pull/15
https://github.com/feedhenry-raincatcher/raincatcher-result/pull/26
https://github.com/feedhenry-raincatcher/raincatcher-risk-assessment/pull/12
https://github.com/feedhenry-raincatcher/raincatcher-schedule/pull/12
https://github.com/feedhenry-raincatcher/raincatcher-signature/pull/16
https://github.com/feedhenry-raincatcher/raincatcher-simple-store/pull/22
https://github.com/feedhenry-raincatcher/raincatcher-sync/pull/32
https://github.com/feedhenry-raincatcher/raincatcher-template-build/pull/11
https://github.com/feedhenry-raincatcher/raincatcher-tutorial-client/pull/6
https://github.com/feedhenry-raincatcher/raincatcher-tutorial-cloud/pull/6
https://github.com/feedhenry-raincatcher/raincatcher-tutorial-module/pull/8
https://github.com/feedhenry-raincatcher/raincatcher-user/pull/68
https://github.com/feedhenry-raincatcher/raincatcher-vehicle-inspection/pull/11
https://github.com/feedhenry-raincatcher/raincatcher-workflow/pull/23
https://github.com/feedhenry-raincatcher/raincatcher-workorder/pull/28

**Comment by wtrocki** [comment]
@paolobueno - you are hero of our times!
I was about to do it today as in ticket! Really great stuff going to review this today!

**Comment by paolobueno** [comment]
@wtrocki I was mostly trying out [this little script](https://github.com/feedhenry-raincatcher/raincatcher-mono/blob/master/scripts/set-version). Lerna needs to manage it's own versions of everything, so I'm just doing stuff manually for now :)

**Pull request merged**
